### ISSUE TITLE
SCREW.cwl not found

### ISSUE THREAD

**Issue by FarahZKhan** [Epigenomics-Screw/Screw#44]
Hi there, 
I am trying to run the cwl workflow using cwltool but the readme file seems outdated. 
Can you please advise on how to run the preprocessing step using "preprocess.cwl"? 
Thanks.

**Comment by yxblee** [comment]
Hi @FarahZKhan ,

The CWL workflow is still a work in progress at the moment, hence the main SCREW.cwl not being available yet. Please check out the dev branch for the most current versions of workflow and script files. 

The preprocess.cwl can be run with our test data via:
`cwltool cwl/preprocess.cwl --toConvert test_data/GSM1589192_K562.1_2.txt.chr19 --format farlik2013`

I hope that helps.

**Comment by FarahZKhan** [comment]
Hi @yxblee, 
Yes this did work :) Thanks for you help.
