### ISSUE TITLE
Generate Methylation BigWIGs

### ISSUE THREAD

**Issue by bdecato** [Epigenomics-Screw/Screw#6]
## Description

As a bioinformatician, I would like to generate bigWIG files containing DNA methylation calls in single cell, in order to speed up downstream plotting and genome browsing.

## Estimate

2 hours

## Priority

MUST

## Notes

- Input will be tsv-like DNA methylation calls, and can be converted to a standard format via Interconvert Methylation Calls
- Output should be one bigWIG file per cell input

**Comment by oneillkza** [comment]
So the code got a bit messy and there isn't a clean PR for this, but it is done and available in the current master branch.
