### ISSUE TITLE
Set up Travis Continuous Integration and Unit Tests

### ISSUE THREAD

**Issue by bdecato** [Epigenomics-Screw/Screw#9]
## Description

As a developer, I would like Travis CI to run a battery of tests using the toy data for every commit and pull request, in order to ensure we don't break anything.

## Estimate

? -- Needs more discussion.

## Priority

SHOULD

## Notes
- Travis doesn't natively support CWL or Docker I don't think. It does have a module for R.

**Comment by neksa** [comment]
It is possible. I found some examples.
See  https://github.com/surf-eds/cwl-examples and 
https://travis-ci.org/surf-eds/cwl-examples/jobs/154676260

`{
  "language": "python",
  "sudo": "required",
  "services": [
    "docker"
  ],
  "install": [
    "pip install -U setuptools",
    "pip install cwl-runner"
  ],
  "script": [
    "cd potreeconverter",
    "./potreeconverter-tool.cwl potreeconverter-job.json",
    "cd ../images2pointcloud",
    "./images2pointcloud.workflow.cwl --help"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
`

**Comment by oneillkza** [comment]
Thanks! That was a very useful template!

OK, it looks like I've got it mostly set up. I'm just letting it run through with the new quay.io repos to be sure, but the infrastructure is all in place. Once those builds are done, I'll make a PR back into the main repo.

https://travis-ci.org/Epigenomics-Screw/Screw/builds/221445680

**Comment by oneillkza** [comment]
And it's done, and continuous integration catches us our first bug! The current Dockerfile doesn't install methpipe...

**Comment by oneillkza** [comment]
Or more precisely, the `symmetric-cpgs` tool from methpipe doesn't seem to be on the path.

Looking more closely, it seems like the install Makefile target for methpipe doesn't actually do anything, so we need to put the binary files on the path manually.

Also as an aside, now that we have both quay.io and Travis triggering off pushes, there's a bit of a race condition when we update the Docker image. Not a big deal, but it does mean we should make sure to re-run Travis after Quay.io is done building when changing the Dockerfile.

**Comment by oneillkza** [comment]
And we have a green Travis button, and I'm calling this closed! :)
